# Permalinks
#

# Setup
title:               Drivenn
tagline:             'Data Science On Demand'
description:         ''
url:                 http://drivenn.eu
baseurl:             ''
plugins:             [jekyll-paginate]
paginate:            5
paginate_path:       "blog/page:num/"

# About/contact
author:
  name:              Jesse Moore
  linkedin:          https://www.linkedin.com/in/jessemoore1/
  email:             datadrivenn@gmail.com

# Custom vars
version:             1.0.0

