# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Lanyon
tagline:             'Data Driven'
description:         ''
url:                 http://lanyon.getpoole.com
baseurl:             ''

# About/contact
author:
  name:              Jesse Moore
  url:               https://twitter.com/mdo
  email:             datadrivenn@gmail.com

# Custom vars
version:             1.0.0
